AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  example-sf-app

  Sample SAM Template for example-sf-app
Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyName: CodeBuildServiceRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Type: NO_SOURCE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            build:
              commands:
                - echo 'Empty BuildSpec'

  WrapperStateMachineSync:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/wrapper_asl.json
      DefinitionSubstitutions:
        stateMachineArn: !Ref SampleCodeBuildStepMachine
      Policies:
        - Statement:
            - Sid: InvokeStepFunction
              Effect: Allow
              Action:
                - "states:StartExecution"
              Resource: !Ref SampleCodeBuildStepMachine
            - Sid: PutRuleonEventBridge
              Effect: Allow
              Action:
                - "events:PutTargets"
                - "events:PutRule"
                - "events:DescribeRule"
              Resource: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule"
  SampleCodeBuildStepMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/codebuild_example_asl.json
      DefinitionSubstitutions:
        projectName: !Ref CodeBuildProject
      Policies:
        - Statement:
          - Sid: InvokeCodeBuildPolicy
            Effect: Allow
            Action:
              - "codebuild:StartBuild"
              - "codebuild:StopBuild"
              - "codebuild:BatchGetBuilds"
              - "codebuild:BatchGetReports"
            Resource: !GetAtt CodeBuildProject.Arn
          - Sid: PutRuleonEventBridge
            Effect: Allow
            Action:
              - "events:PutTargets"
              - "events:PutRule"
              - "events:DescribeRule"
            Resource: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventForCodeBuildStartBuildRule"


  WrapperWithWaitStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/wrapper_waitForTaskToken_asl.json
      DefinitionSubstitutions:
        stateMachineArn: !Ref SampleCodeBuildWithCallbackStepMachine
      Policies:
        - Statement:
            - Sid: InvokeStepFunction
              Effect: Allow
              Action:
                - "states:StartExecution"
              Resource: !Ref SampleCodeBuildWithCallbackStepMachine

  SampleCodeBuildWithCallbackStepMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/codebuild_example_withToken_asl.json
      DefinitionSubstitutions:
        projectName: !Ref CodeBuildProject
      Policies:
        - Statement:
          - Sid: InvokeCodeBuildPolicy
            Effect: Allow
            Action:
              - "codebuild:StartBuild"
              - "codebuild:StopBuild"
              - "codebuild:BatchGetBuilds"
              - "codebuild:BatchGetReports"
            Resource: !GetAtt CodeBuildProject.Arn
          - Sid: PutRuleonEventBridge
            Effect: Allow
            Action:
              - "events:PutTargets"
              - "events:PutRule"
              - "events:DescribeRule"
            Resource: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventForCodeBuildStartBuildRule"
          - Sid: SendSuccess
            Effect: Allow
            Action:
              - "states:sendTaskSuccess"
            Resource: "*"


Outputs:
  SampleCodeBuildStepMachineArn:
    Description: Stock Trading state machine ARN
    Value: !Ref SampleCodeBuildStepMachine
  SampleCodeBuildStepMachineRole:
    Description: IAM Role created for Stock Trading state machine based on the specified
      SAM Policy Templates
    Value: !GetAtt SampleCodeBuildStepMachineRole.Arn
# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
